// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vUqt3LUpwRMQ4CpFYXzjSE6XAFyIU5g',
    appId: '1:986762918096:web:40ceca69111cfc989606d5',
    messagingSenderId: '986762918096',
    projectId: 'whatsapp-clone-app-29f52',
    authDomain: 'whatsapp-clone-app-29f52.firebaseapp.com',
    storageBucket: 'whatsapp-clone-app-29f52.appspot.com',
    measurementId: 'G-J7NZ0JWWM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaWpO_li-evSsJ4czRcm6yTY4d1zxYTSM',
    appId: '1:986762918096:android:984d796b733603f29606d5',
    messagingSenderId: '986762918096',
    projectId: 'whatsapp-clone-app-29f52',
    storageBucket: 'whatsapp-clone-app-29f52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARaZq6SqyMynm4X0x7JxOHQNoAiyrBZKk',
    appId: '1:986762918096:ios:85e74910a48c79399606d5',
    messagingSenderId: '986762918096',
    projectId: 'whatsapp-clone-app-29f52',
    storageBucket: 'whatsapp-clone-app-29f52.appspot.com',
    iosClientId: '986762918096-m2mmm4ikaq7fndvgv5rgabfousjsk9od.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappCloneApp',
  );
}
